#!/bin/bash

if [ -f "/boot/hostname" ]; then
	CURRENT_HOSTNAME=`cat /etc/hostname | tr -d " \t\n\r"`
	NEW_HOSTNAME=`cat /boot/hostname | tr -d " \t\n\r"`

	echo $NEW_HOSTNAME > /etc/hostname
	sed -i "s/127.0.1.1.*$CURRENT_HOSTNAME/127.0.1.1\t$NEW_HOSTNAME/g" /etc/hosts

	mv /boot/hostname /boot/hostname.set
	echo "Set hostname to ${NEW_HOSTNAME}. Rebooting..."
	reboot
fi
